#spring datasource config
spring:
  datasource:
    initialize: false
    url: jdbc:mysql://172.17.246.55:3404/ppdai_forbeginners_devstandard?useUnicode=true&characterEncoding=utf-8
    username: root
    password: abc@123
     # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /templates/
      suffix: .html

common:
  jdSecret: 2b4270dc0adfe881f3e301d72346b00c
server:
  port: 9013

mybatis:
  type-aliases-package: com.zxxz.lv.entity
  mapper-locations: classpath:mapper/*.xml
